config:
  use_model_name: "resnext101_32x8d"
  use_gpu_num: 1
  train_data_path: "I:/work/WORK/ReclassifyAnimeCG/ReclassifyAnimeCG/data-sample/train"
  test_data_path: "I:/work/WORK/ReclassifyAnimeCG/ReclassifyAnimeCG/data-sample/test"
  output_data_path: "I:/work/WORK/ReclassifyAnimeCG/ReclassifyAnimeCG/data-sample/output"
  predict_data_path: "I:/work/WORK/ReclassifyAnimeCG/ReclassifyAnimeCG/data-sample/predict"
  cv_train_ratio: 0.7
  cv_val_ratio: 0.15 # the test data will be generate by 1 - cv_train_ratio - cv_val_ratio
  copy_test_result_to_output_path: false
  filter_train_data_in_test: true
  delete_duplicate_images_before_training: true
  models_parameter:
    resnext101_32x8d:
      batch_size: 16
      image_input_size: 300
      max_epoch: 100
      resume_epoch: 0
      weight_decay: 5e-4
      momentum: 0.9
      lr: 1e-3